# Generated by Django 3.2.7 on 2021-11-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(verbose_name='user_id')),
                ('assesory', models.CharField(choices=[('Informacion', 'Informacion'), ('Instalacion', 'Instalacion'), ('Quejas y reclamos', 'Quejas y reclamos')], max_length=50, verbose_name='Assesory_type')),
                ('comment', models.TextField(blank=True, max_length=600, null=True, verbose_name='Comment')),
                ('is_active', models.BooleanField(verbose_name='is_active')),
                ('response', models.TextField(blank=True, max_length=600, null=True, verbose_name='Response')),
                ('date_create', models.DateField(verbose_name='Date_create')),
                ('date_response', models.DateField(verbose_name='Date_response')),
            ],
        ),
    ]
