# Generated by Django 3.2.7 on 2021-11-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='assesory',
            field=models.CharField(choices=[(0, 'Informacion'), (1, 'Instalacion'), (2, 'Quejas y reclamos')], max_length=50, verbose_name='Assesory_type'),
        ),
    ]
