# Generated by Django 3.2.7 on 2021-11-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0003_auto_20211117_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='assesory',
            field=models.CharField(choices=[(0, 'Informacion'), (1, 'Instalacion'), (2, 'Quejas y reclamos')], max_length=50, null=True, verbose_name='Assesory_type'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_response',
            field=models.DateField(null=True, verbose_name='Date_response'),
        ),
    ]
