# Generated by Django 3.2.7 on 2021-11-18 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Installation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='machine_type',
            field=models.CharField(choices=[(0, 'Granos'), (1, 'Granos chicos'), (2, 'Mayor capacidad'), (3, 'Maquina estandar')], max_length=50, verbose_name='Machine_type'),
        ),
    ]
