# Generated by Django 3.2.7 on 2021-11-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Installation', '0002_alter_installation_machine_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='date_create',
            field=models.DateField(auto_now_add=True, verbose_name='Date_create'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='date_response',
            field=models.DateField(auto_now_add=True, verbose_name='Date_response'),
        ),
    ]
